### ISSUE TITLE
Using TParameter to save numbers

### ISSUE THREAD

**Issue by maxfl** [mjkramer/IbdSel#2]
Just in case, you may use `TParameter<float>` to save numbers in a ROOT file. You may find an example in 984d67d (a bit spoiled with other files).

https://root.cern.ch/doc/master/classTParameter.html

**Comment by mjkramer** [comment]
Nice, I didn't know about TParameter. But for now I am sticking with histograms and trees in the stage2 outputs so that I can "hadd" them together.
